name: Build and Commit with npm

on:
  push:
    branches: [main]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"   # Schleifen verhindern
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Token weiterreichen, damit ein Push erlaubt ist
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0        # komplette Historie, sonst kann push fehlschlagen

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci --legacy-peer-deps   # reproduzierbarer als npm install

      - name: Build
        run: npm run build               # erzeugt lib/

      - name: Commit built files
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # ignorierte Dateien erzwingen
          git add -f lib/

          # Nur committen, wenn sich wirklich etwas geändert hat
          if ! git diff --cached --quiet; then
            git commit -m "build: auto-commit lib [skip ci]" --no-verify
            git push origin HEAD:main
          else
            echo "no changes"
          fi
